* README for DSOrganize
** DSOrganize is originally written by DragonMinded
*** Edited by Jesse N. Richardson (Flare183)
**** DragonMinded's DSOrganize Revision History:
3.2

Added multi track support to SID files (finally!).
Added support for the gbs file format.
Added confirmations to text editor on save or exit.
Added /describe to irc.
Added basic cookie support.
Tied Y to the stop function on the web browser.
Changed IRC receive mode to hopefully squash memory error.
Changed internet enabled applications to allow downloading/processing while the lid is closed.
Decreased memory footprint to allow larger images to load again.
Fixed annual dates causing every day to underline in some cases.
Fixed e^x freezing in some instances.
Fixed inconsistent save message on scribble screen.
Fixed IRC bug that appeared while typing with fixed width irc.
Fixed aac/mp3 streams skipping sometimes.
Fixed bad font characters in the smallest font.
Fixed a html rendering crash with css pages.
Fixed random crash that happened when switching tabs in web browser.
Fixed garbage display in hbdb if you cancelled the list then pressed left or right.
Fixed graphical issues with themes loaded.
3.1129

PNG files now support proper alpha channel.
Added server-based auto perform to irc.
Added missing ascii characters to all fonts, changed some fonts slightly.
Added SSL support to web browser.
Fixed side tab icons not showing up when startup screen was irc or web browser.
Fixed random crash on shutting the lid.
Fixed inconsistent help messages on configuration.
Fixed more incorrectly written pages that don't display.
Fixed deflate raw encoding not working.
Fixed random scroll down on pages that fit entirely on top page while on favorites.
Fixed invalid directory configuration message not showing up.
Fixed orientation messing up when viewing pictures in web browser.
Fixed some image placeholders overlapping each other before rendering.
Fixed disappearing cursor on scribble pad.
Fixed graphics corruption on side tabs with other themes.
Disabled help from appearing while files are downloading in web browser to stop freezes.
Updated dswifi to 0.3.4
3.1

Added support for attachment style downloads (usually download.php style).
Added deflate and gzip encoding support to web browser.
Added letter view mode to the picture viewer.
Added optional click noise to keyboards.
Added many more special character tags like &egrave; etc to web browser.
Changed large font to Arial 13 from Century 16 to be more consistent.
Fixed download filenames being badly named when longer filenames were downloaded beforehand.
Fixed "Removing invalid lfn entry" error in FAT after deleting a file.
Fixed "Invalid file size on entry" error in FAT after creating a new empty file.
Fixed "Errors in . and/or .. corrected" error in FAT after creating new directory in root.
Fixed files randomly not being created and "directories after end" error in FAT.
Fixed seek bar not updating while paused.
Fixed text boxes getting the generic text color instead of the textbox text color.
Removed plugin architecture and resources file. Were causing too much trouble with no real benefit.
3.05

Added extra checking to the image parser code to hopefully stop more freezes.
Added back in ability to create lowercase filenames that are short.
Added bad file check to gba_nds_fat so corrupt files shouldn't freeze DSO anymore.
Added ability to download files on web browser.
Added auto-hide setting to web browser.
Changed default progress color on web browser to be more visible.
Changed all audio formats that read on interrupt to read from a buffer.
OGG, AAC, M4A files play faster now.
OGG, AAC, M4A, MP3 files more stable.
Fixed a bug in the downloader code that added garbage extensions to some images, making sites crash.
Fixed a bug in the mp3 player that detected some stereo songs as mono, decreasing the quality.
Fixed directory sort order bug.
Fixed bug where sites using <script src="file" /> notation would not render.
Fixed a few buffer overflows in web browser which should increase stability.
Fixed a bug where uppercase hex digits converted to zeros in WEP keys.
Fixed not being able to clear WEP keys.
Fixed issue with random freezes while using the touchscreen in the sound player.
Fixed random seek crashes with aac/ogg/flac/m4a.
Fixed link issue with some php links.
Fixed a bug with saving favorites.
Fixed a bug where the cursor wouldn't auto-scroll when editing text.
Fixed a disappearing cursor bug with fixed width text editing.
Fixed a bug with sites that used bad tags like <br/> instead of <br />.
Fixed a bug that allowed todo's with illegal characters to be created.
Fixed a crash bug with small png images that run out of memory.
Fixed several out of memory crashes with web browser in general.
3.01

Added basic signal strength to wifi configuration screen.
Fixed error messages not being readable on startup.
Fixed wifi to be slightly faster again.
Fixed seeking broken on some file formats.
Fixed SSID not centered properly.
Fixed 256x192 images not showing the bottom line.
3.0

Added select/cut/copy/paste to all text inputs.
Added wifi config (including saving back to firmware) with three extra DSOrganize profiles.
Added ability to bookmark on the web browser by pressing ctrl + b.
Miscelaneous fixes to the HTML renderer.
Fixed error in file wrapper causing bad file copies.
Fixed a weird lingering cursor bug in text editor.
Fixed startup screen error.
Fixed an error where images that redirect would change the url of the main page loading.
Fixed a bug with sites that use 1x1 tracking images.
Fixed error where confirm delete screen on browser allowed you to select ".." or "."
Fixed some weird bugs with m3u files.
Fixed select few files not showing their long file names.
Fixed everything being underlined on sites with bad <a> tags (ds-x.com, etc)
Day planner now supports weekly, monthly, and annual events.
Day planner events are now partially visible on reminder mode.
Todo now sorts finished events as last.
Changed handling of escaped characters to include the limited unicode support.
Changed irc to not display characters under 32 on the ascii map.
Updated dsWifi again for compatibility.
2.9 NeoFlash

Added small images rendering!
Added simple CSS parsing!
Added colors reset character parsing to irc.
Added .sndh playback.
Added 24/32bit wav playback.
Added ability to put a custom colors.ini inside an iconset directory.
Added ability to view full-size images if they are linked to (eg. 4chan).
Added left handed mode!
Added ability set fixed width font to irc and text editor.
IRC text no longer gets added to the command backlog if it already appears somewhere in the backlog.
Changed handling of ul/ol tags to make slashdot render better.
Changed display method of forms to make elements space out better.
Changed html parser to check for text colors that are the same as the background for sites that rely on a background image to display text properly.
Changed streaming audio buffer method to hopefully fix buffer underruns on some streams.
Changed redirect method to hopefully fix the few nonworking sites.
Updated dswifi to latest CVS to allow people with 512K firmwares to use DSO online.
Updated plugin architecture to have better controls drawing functions.
Fixed issue where favorites would accidentally load if you clicked favorites before it finished authenticating.
Fixed a parsing error with single quotes in href or src elements.
Fixed an issue where a carriage return/line feed inside an <a> tag would cause link clicking to fail.
Fixed a bug in the fat library that caused some directory configurations to hang or not list properly.
Fixed a few bugs in animated gif files so more animated gifs play properly.
Fixed random gibberish bug on web browser if you click past the end of the list.
Fixed ability to click past the end of the list on homebrew database.
Fixed slight graphic glitch with scrollbar on homebrew database.
Fixed keyboard repeat not working on IRC or web browser.
Fixed a playback issue with mp3 streams.
Fixed a crashbug with certain animated gifs.
Fixed a display bug with certain text files on the web browser.
Fixed IRC not sending quit message.
Fixed having to be named bootme.nds on datel products.
Fixed out of memory error after clicking a form, exiting, and reentering the web browser.
Fixed issues pertaining to startup sounds.
Fixed bug where exiting browser while downloading a page caused the filesystem to freeze until reboot.
Fixed potential crashbug with downloading some sites.
Included updated bootloader from Chishm to fix booting on many devices.
Vastly improved sid playback sound.
Remade home screen to allow for another shortcut.
Remade configuration screen to be less confusing and more organized.
2.8 GBAX

Added referer header tag to the web browser.
Added plaintext viewing to the web browser.
Added customizable shortcut keys to web browser.
Added rudimentary favorites to web browser.
Added captured urls from irc to web browser.
Added homepage option to web browser.
Added colors/bold/underline input to irc.
Added clickable nick list to channels on irc.
Added setting to disable autopatching.
Added startup sound.
Added sound notify to IRC when you recieve a new PM or your name is said in channel.
Added highlight when your name is said in channel on IRC.
Added option to disable writing to card.
Changed how the playback mode saving works to hopefully fix the freeze.
Changed the way the html parser looks for body tags to make malformed pages render.
Changed web browser to swap to text entry mode automatically when clicking entry forms.
Changed the way urls are handled to allow for much larger pages to display (e.g. wikipedia iran page).
Fixed lockup issue with downloading homebrew.
Fixed a stack overflow issue with the web browser.
Fixed DSO letting you into wifi-capable apps on startup if resource0.bin is missing.
Fixed crash in web browser when sites have malformed tag properties (babelfish fixed).
Fixed crash in web browser when sites use more than six digits in a color (babelfish again).
Fixed bug in web browser where form elements could remain bold/italics/underlined/strikethrough.
Fixed bug where calculator button colors wouldn't set.
Fixed a parsing error with homebrew database package files that include spaces or cr/lf in the wrong spot.
Fixed a parsing error with web sites that use hexadecimal in their character codes.
Updated dsWifi library for the latest dslite fix.
Updated the loading bar for web pages.
Made send buffer larger so forms don't sometimes crash web browser.
Made DSOrganize auto-clear browser cache on entry and exit of browser.
Made DSOrganize not turn off the backlight when in recording mode to stop cutting off sound.
Made DSOrganize save the eight custom colors in scribble between sessions.
Disabled visited link coloring (slowed down load times and added little benefit).</ul>
2.7 Final

Added DLDI file loading for chishm launcher.
Added DLDI autopatching for launched nds files.
Changed IRC to strip leading and multiple spaces.
Disabled touch access to disconnect button on IRC.
Fixed skipping error with select few mp3s and most mp3 streams.
Fixed browser freeze when pressing R after re-entering browser.
2.7 Beta

Massive overhaul to the sound system allowing for vastly superior sound:
Modules are now played at 44100 instead of 22050 frequency.
Wav files don't stutter anymore on higher bitrates.
Oversampling for .mpa/mp2 files brought up to 2x.
Oversampling for .mp3 files brought back to 4x (streams stay at 2x).
Sped up .m4a/.m4b decoding so higher bitrates play.
Oversampling for .aac files brought up to 2x (streams stay at 1x).
Fixed slight skip heard in some .flac audio files.
.nsf file are now played at 48000 isntead of 40000 frequency.
Oversampling for .sid/spc/nsf files is now up to 2x.
Fixed the weird echo issue with .spc files.
Overhaul to the HBDB system allowing for much better databases:
Changed the way that the HBDB sorts files, allowing for categories and more card types.
Changed the way that the HBDB detects the dsorganize or root directories.
Changed the downloader system to be more robust.
Added simple web browser!
Added eq meters to .flac and .m4a/m4b/aac files.
Added left and right d-pad support to browser and web browser to act as page up and page down.
Added ability to edit m3u and pls files on the fly in the text editor.
Added chishm's DLDI loader to DSOrganize. This fixes booting on MMD.
Added support for cellspacing/cellpadding in tables (mostly makes fark.com readable).
Changed </tr> tag to add a line break if not already present.
Changed the way the HTML renderer recognized header and body positions, fixing several pages.
Changed IRC button mapping to be more consistent with other apps and stop accidental disconnects.
Changed local HTML file viewer to show title.
Changed IRC channel windows to display the number of people in the channel.
Fixed a wrapping error with long HTML files.
Fixed <p> rules to reflect optional end tag.
Fixed <a> tags erasing bold property.
Fixed underline placement for large font.
Fixed an error in the html render with scripts containing < in them.
Fixed HTML pages that use & in the text improperly.
Fixed <a name> tags to not change the style of text.
Fixed an issue with <a> tags that didn't contain name or href elements.
Fixed HTML renderer to properly ignore carriage returns.
Fixed a bug with homebrew downloader percentages.
Fixed the major issue with corrupting directories. This does not fix the problems with some M3 devices as the driver is defective for them.
Fixed bug where html tag properties with > in them would prematurely end the html tag.
Fixed some memory leaks on the home screen.
Fixed bad command handling on the IRC windows.
Fixed an error with bookmarks in HTML local files..
Removed ninjaDS driver as it can be patched in and has long load times.
2.61

Fixed incorrect sprite for calendar error.
Fixed error in the INI parser for colors that caused black keyboard bug.
Fixed inverted background color bug on scribble editor.
Fixed DSOrganize not booting on NeoFlash cards!
Worked on NSF unresponsive keypad.
Worked on SPC sound a bit. Some of the echo is due to the library I used, sorry.
Changed volume control to allow less than 100%.
Changed browser to remember the last position of the cursor in each directory.
Started new project of separate compiles per device of exec_stub.bin
GBAMP specific build: WORKING
R4/M3 Simply specific build: WORKING
DLDI generic build: WORKING in some cases
2.6

Sped up text display routines a lot, helping with larger text and html files.
Vastly improved HTML rendering mechanism, large HTML files don't bog down any more.
Switched to latest dsWifi from CVS as it no longer freezes on my DS.
Added <q>, <dt> and <dd> to HTML renderer.
Added flac support to the sound player.
Added primitive sid support to the sound player.
Added nsf support to the sound player.
Added spc support to the sound player.
Added ability to check card type in plugins.
Added ability to move the cursor with the stylus on the configuration and irc pages.
Added ability to customize colors with colors.ini file.
Changed the sound player volume maximum to 400%.
Changed vCard loading to load simple unicode files, though only ascii charset is supported still.
Changed behavior of HTML renderer when leaving <TD> tags to fix bad HTML coding.
Changed behavior of default settings creator to direct people to the correct IRC server.
Fixed issue where keyboard repeats didn't work on the configuration screen.
Fixed screen swap glitch with text input box on the scribble pad.
Fixed potential bug with vCard separator, fixed naming issue with vCard separator.
Fixed slight issue with mp3 playback clicks, but had to take oversampling down to 2x.
Fixed memory leak in plugin loading.
Fixed <pre> tag not changing to fixed width.
Fixed bug in HTML syntax highlighting with more than one tag property that wasn't quoted.
Fixed language being wrong issue when there is no config.ini file.
Fixed issue where L and R GUI widgets were not clickable on picture viewer.
Fixed a wordwrapping bug that popped up on the IRC window affecting scrolling.
Fixed text color inconsistency on configuration page 3.
Fixed issue with help screens and absolutely no help pages available.
2.5

Worked on making DSOrganize take up less memory on its own for more plugin memory.
Switched to more dynamic approach for plugins. Things should work better now.
Changed home screen to display current and next two day planner events instead of past ones.
Changed plugin vblank handling to give dedicated vblank access to plugins/exes when run.
Changed some code on the arm9 recieve fifo queue, hopefully fixing the random sound/keyboard freeze.
Changed arm7 upsampling code to sound better for amplified mp3's.
Changed calculator memory usage to allow for larger numbers.
Added in newest ogg vorbis memory leak fix.
Added echo, cls, wait commands to homebrew database script.
Added ability to swap buffers on only the top or bottom screen in plugins.
Added ability for plugins to query which screen DSO is on (for those that hook to the draw function).
Added simple battery saver function and debug write to disc function to plugin API.
Added repeat to all keys in the keyboard and fixed a glitch where char 255 couldn't be typed.
Added .dss shortcut type. Shortcuts can point to any file or directory except for another shortcut.
Added access to the PSG on the arm9 for plugins.
Added the missing commands for dswifi to the plugin API.
Fixed erasor glitch in scribble.
Fixed weird wrapping glitches introduced after the text fix.
Fixed glitch in syntax highlighting for html files introduced after text fix.
Fixed glitch where if resource0.bin is missing, DSO does not jump to your preferred start page.
Fixed error with ID3 tags containing a carriage return/line feed.
Fixed crash on loading iconsets from directories longer than 29 characters.
Fixed two irc crash bugs relating to bad server replies (ie on irc.enterthegame.com).
Removed mikmod loaders for all types but xm, it, s3m, mod due to low popularity.
2.45

Increased state field on address displays to be 3 long instead of 2.
Changed boot function code, hopefully making the arm7 a bit more stable.
Updaded dldi driver to newest version, should fix problems with some .ds.gba and .sc.nds files.
Fixed work address display issue with vCards.
Fixed address crash/corruption on second entry to address screen.
Fixed crash on sample language bug.
Fixed sqrt button not working in calculator.
Fixed scrollbar in text reader not showing highlighted status.
Fixed massive slowdown with some text files in browser.
Fixed bug with mono mp3s and skipping.
Added icon and description to plugin files in the browser.
Added DSO executable type for standalone apps.
Added raw stream API to plugins and executables.*
Added more commands to help text in IRC.
2.41

Changed driver structure to allow better supercard support, built in m3cf support.
Changed version string to properly reflect the version.
Fixed issue with loading IRC configuration.
Fixed issue with some langauges and random freezes/browser errors.
Added check for resource0.bin and added warning message if it's not found.
2.4

Fixed the infamous crash bug in IRC when someone parted with a message. (This one was hard to find!)
Fixed some translation issues with the Configuration page.
Fixed bug in .sd.nds and .ds.gba booting.
Fixed text wrapping errors on rename file and address book screens.
Fixed help text stuck on screen in sound player after viewing help.
Fixed another parsing error with vcards.
Fixed clipping issue with spray bottle tool in scribble pad.
Fixed issues with displaying some error messages in irc.
Fixed inconsistency with nds launcher and cards not supported by built-in loader.
Fixed issue with gautami font and some upper ascii characters being mapped wrong.
Fixed a minor streaming buffer bug that seems to help with stability.
Fixed pausing streams caused streaming to crash.
Added dynamic loading of code for DSO specific plugins.
Added customizable iconsets.
Added .aac playback.
Added m4a/m4b file playback. The DS is too slow for higher bitrate m4a files but lower bitrates should work.
Added irc.ini file where users can customize DSO IRC.
Added descriptions to most of the settings in the configuration.
Added in fallback so foreign languages without help translations will still display english help.
Added ability to choose specific streams within a .pls file.
Added several commands (topic, mode, invite, kick, motd, version, ping, time, ctcp, whowas) to irc.
Added new dldi interface to allow patching to new/unsupported cards.
Added ogg vorbis streaming support in shoutcast and icecast servers.
Added aac streaming support in shoutcast and icecast servers.
Added an easter egg. See if you can find it!
Added setting so DSOrganize remembers the last playback mode.
Added legend to todo screen in help.
Added m3u playlist support.
Added symbols for copyright, registered, trademark, euro, pound, and yen to the character set.
Changed random mode in playback to act more like shuffle.
Changed picture loading screen to just moving bar, as progress was terribly inaccurate.
Changed hilighting style on menus.
Changed streaming detection to properly support iceCast streams.
Changed buffer behavior on streams to buffer to 200% and more vigorously, for longer stream times.
Changed .pls file parser to allow regular file playlists.
Changed browser pull-up menu support to be easier to get to.
Initialized volume to stop the 500% error when booting from moonshell.
Re-ported tremor and mad for much better audio playback.
Updated dswifi library to latest as usual.
Stopped scrollbar from appearing on very short html files.
Looked at microphone code, no real way to make the quality better due to speed of writing.
Redid home screen splash to instead be an overview of the day.
Made it so the browser doesn't sequentially or randomly play playlist files in sound mode, and changed the playlist icon.
Rewrote a lot of the HTML renderer. It renders slower now, but will load much much longer pages.
Fixed weird wordwrap issue with multiple font sizes
Fixed a bug with style tags at the very end of an html file
Fixed a bug where opening a page with different colored links left all pages displaying that link color.
Added bullets and numbered lists
Stopped extra whitespaces from appearing
Changed formatting for <div> and <p> tags
Added <hr>, <big>, <tt>, <code>, <strike>, <h6>, <frameset> with <noframes>, <sub>, <sup>, <em> <strong>, <cite>, <dfn>, <var>, <samp>, <kbd>
Ignores <script> and <style> tag contents instead of rendering as text
2.3

Fixed bug where A/B didn't swap on sound player.
Added volume multiplier to sound player.
Added extra characters for spanish users.
Fixed bug with ? always being highlighted when old language files were used.
Made all screens with scrolling lists wider, to use up the unused border space and changed the look and feel a bit.
Changed text/html viewer scrollbar to reflect being held like other scrollbars.
Changed HBDB to stay in / if the default homebrew path isn't found.
Fixed a bug where scribble saves were getting corrupted from an old home screen.
Made /connect an alias to /server.
Made IRC ignore commands it doesn't know.
Made left and right buttons jump to previous/next day planner events like the bookmark system.
Added pull-up menu to browser. Drag your stylus from one of the buttons upwards to activate.
Fixed bug with L/R highlighting in IRC.
Fixed some inconsitencies in the help files.
2.25

Fix for crash when nick is too long for server and you are autoconnecting.
Made DSOrganize IRC auto-pull nick from firmware if none is given.
Added alternate nick setting to DSO IRC.
Disabled the ability to type spaces in nickname entries on configuration.
Added check for bad server connections.
Changed scroll buffer on each page to only hold the last 100 lines.
Fixed ping command to not send until at least you are connected properly.
Made DSO check for valid path entry of HBDB download directory.
Fixed homebrew database to download into the dsorganize directory properly if it is /data/dsorganize/.
Added check for renaming to no file name to be more idiot-proof.
Took out MK2/MK3 and NinjaSD drivers for Green and Blue release to speed boot times (whiners).
Fixed the long hang time on hiding and unhiding files.
Added new supercard drivers to Blue release to hopefully fix scLite.
Reorganized configuration a little and added a few more options.
Added in option to change the default homebrew boot method.
Added in option to automatically insert bullets on the todo screen.
Added in option to swap the A and B button on all screens.
Fixed sluggishness on calculator buttons.
Fixed streams to use proxy if needed.
Made IRC advertise the /help command when starting up.
Changed L and R buttons on IRC to highlight the appropriate color if an offscreen window gets a message.
Added typed backbuffer on IRC. Hold Y and use the up or down buttons to scroll up to five lines back.
Added page-up and page-down to irc. Hold X and use the up and down buttons to scroll the view.
Changed /data/ directory detection method to only work if /DSOrganize/ directory is present inside.
Changed browser interface so that if there are multiple options for a file, A always views and Y always edits.
Added .hbdb and .pkg as editable file types.
Fixed some rendering errors in the simple html renderer.
Fixed weird error in syntax hilighting.
Fixed syntax hilighting logic for comments and html editor.
Fixed a bug where you were allowed to rename or delete the . and .. entries, thus destroying the file structure.
Fixed underlining error with links at the end of html files.
Added /away to IRC.
Added a failsafe in the FAT_rename code, hopefully this fixes dropped entries.
2.2 Final

Fixed a few more screen inconsistencies with the keyboard.
Fixed launch alternate in browser being labeled as record.
Fixed pageup/pagedown not working via touchscreen on text editor.
Fixed the freeze bug and graphic corruption in the text editor with page up and down.
Fixed a bug with the default download directory in the homebrew database.
Updated fat library to reflect newest fixes by chishm.
Supports slower SD cards that wouldn't init before.
Supports Max Media CF (unverified) and Ninja SD (tested working)
Touchscreen and keys are now responsive again in the audio playback modes.
Added in touch code for next/previous functions on audio playback screen.
Renaming is now instant and allows you to change capitalization, and works on directories.
Delete works on directories, and will recursively delete if the directory is not empty.
Added mkdir command to browser.
Added cut/paste command for people who want to move instead of copy.
Worked on sound code some more, it isn't going to be possible to add volume in, my code is apparently too slow.
Added primitive support for ogg vorbis info.
Added some settings to the configuration page.
Changed a couple icons in the program.
Added second click option to Address, Todo, Scribble, and Homebrew Database screens.
Fixed a bug where the last icon on the second page of the home screen didn't have a caption in other languages.
Fixed the sorting bug with DD/MM/YY display under Homebrew Database.
Added sanity checks to all commands in IRC.
Fixed a join bug with bad server replies in IRC.
Added TIME and PING CTCP replies in IRC.
Added missing KICK command to parser.
Added autoperform to IRC. Put any commands you want to perform on connect in autoperform.txt in the DSOrganize root data directory. Sparate each command on a different line.
Fixed color scheme for server versus client error messages.
Fixed a bug in changing nicks that could cause DSO IRC to crash.
Updated wifi lib again.
Fixed crash from pressing Y on browser with an NDS highlighted when running from non GBAMP/SC.
Added ninjaSD as a possible card type on the homebrew database.
Added custom HBDB package files to browser. Simply place the script for your custom download into a text file and save as a ".pkg"
Added custom HBDB connect url files to browser. Place the base url into a text file and save as a ".hbdb" Note that custom HBDB databases do not recieve the card that DSOrganize runs on.
Fixed calculator freeze bug with e^x and other things. This was due to the m_apm library not having a return function to tell how long the string would be, so I had to modify it myself.
Fixed a calculator bug when pressing two binary operators after another performed the first instead of changing to the second.
Changed equals key to repeat the last binary operation, like a real calculator.
2.2 Preview 2

Fixed the random crash bug when pressing enter in IRC.
Made it so the /cls and /help commands can be typed anytime into any window on irc.
Fixed the swap button not being touchable under the text editor.
Compressed and edited some more graphics for a smaller file size.
Added a help file for IRC.
Made enter key function the same as the A key on the keyboard in new file/rename file for better integration.
Fixed a typo in the help files.
Deleted references to handwriting recognition in help files.
Fixed display of png files with alpha channels.
Changed the default loading routine for nds files to mighty max's new loader. DSOrganize should now load most .nds, .sd.nds, and .ds.gba files on any card type supported.
DSLinux booting is now supported on GBAMP again!
Press Y to alternate load with the old loader.
Changed configuration to include IRC as a default screen.
Added 0 to MEDS keyboard.
Fixed screen inconsistencies that happened sometimes while typing.
Added /raw and /quote messages to IRC.
Fixed an error with underlining all 31'st of the month if any of them had a Day Event on them.
Fixed a bug where the day planner wouldn't load the current day event when loaded.
Fixed a bug where calendar events on the 31'st were not hilighted.
Fixed a bug where calendar events weren't properly refreshed when loaded.
Made sound louder on recorder, switched to 22050 hz instead of 11025.
Added [x] as a delete key under Todo and Address screens.
Added check so vCards and Todo filenames can no longer have invalid characters such as ? in them.
DSOrganize now automatically separates multiple vCard entries into separate files.
Made DSOrganize check for all proper subdirectories to ensure unzipping to card went fine.
Made DSOrganize touch keyboard a wee bit more accurate.
Changed DSOrganize directory structure to support a unified /data/ directory on card. If DSOrganize detects the /data/ directory on your card, it will automatically assume it should be placing it's DSOrganize directory inside it, if not, it continues the way it did before.
2.2 Preview 1

Fixed a weird bug in html syntax hilighting.
Realigned all text that was above keyboards to make it look better.
Possible support of the EZ4SD series. Please give feedback.
Started IRC client. Configuration for now is located only in the ini file.
Further worked on keyboard accuracy/speed, it is very nice now.
Fixed L/R bug in browser confirm delete.
2.1

Fixed wav playback bug!
Fixed crash bug relating to extremely long file extensions (thanks BackBon3)
Fixed issue with saving bookmarks.
Fixed some issues with shoutcast playlists and streams.
Fixed a weird issue with renaming.
Changed vCard parsing, should be far more compatible with vCard files now, especially vCard 3.0.
Changed calendar/day planner written dates to reflect DD/MM/YYYY setting
Changed bookmarks to auto delete oldest one when you add more than the maximum.
Added default homebrew save path. Edit the ini file for this option.
Added .cfg as a text type.
Added sort by date option on the homebrew database.
Added messagease keyboard style.
Added support for 8bit wav playback.
Added simple proxy support. See the ini for details.
Added support for loading many more tracker formats, and mp2.
Added wav file recorder for voice memos.
Recoded keyboard from scratch, making it bigger, and fixing the shift bug.
Took out crappy handwriting recognition.
Improved keyboard speed by a bit, hopefully making typing easier.
2.01

Added new fields to homebrew database: date, version, size of package.
Reverted from eabi back to r17 due to regresses:
Fixed .xm crash regress.
Fixed supercard boot failure crash.
Possibly fixed crash relating to ani gif files.
Improved key responsiveness on module player.
Fixed issue with shoutcast url's with no trailing / not loading properly.
Changed fat lib to rein r15 modified. Hopefully this works with M3 SD.
Fixed transparency issue with NDS file icons (Thanks LiraNuna).
Fixed issue with nds icon for dsorganize having bad transparency.
Changed file code to allow icons/descriptions for .sd.nds and .ds.gba files.
Fixed cursor bug in text editor with page down and files less than 11 lines long.
Homescreen highlights last app used when exiting back to it.
Fixed a bug relating to pressing y while hilighting a .ini file in browser.
Allowed homescreen customization, edit in the .ini for now.
Fixed minor bug with copying file then creating a new file without pasting.
Changed the way alternate browser modes function.
Added click to edit on calendar and day planner.
Fixed a weird bug with homebrew database scrolling.
Added setting for DD/MM/YY display.
Added setting to enable or disable second tap action.
Added setting to change the html renderer for better compatiblity.
Upgraded to latest tcplib, hopefully this fixes more issues.
2.0

Browser automatically renames associated .bmf files when you rename txt/html files.
Audio player now has random history, so you can go back in random mode.
Fix to @ in arial 9 to not be cut off on the bottom.
Made some changes to the HTML renderer.
Fixed ID3v1 text to be translatable.
Fixed issues with "Toggle Hidden" text in browser and sound player.
Started adding shoutcast streaming support.
Changed mp3 multiplicity from 2 to 4, hopefully making it sound even better.
Finished homebrew database version 1.
Fixed scribble bug where screens became reversed after shuttin the top.
Found and fixed a memory leak pertaining to keyboard inputs.
Found and fixed a few other small memory leaks.
Worked on GBAMP/SC booting a bit, hopefully it works a tad better.
1.9 Final

Changed INI keynames to bold black, items to blue, like html syntax hilighting.
Made browser take off .sc for .sc.nds files on top screen.
Fixed text overflowing bug in browser display top screen.
Fixed text overflow bug and shortening bug in todo, address and scribble applications.
Fixed edit calendar date bug.
Fixed the crashes when turning the screen off or on.
Fixed graphics corruption when lid was down and songs changed.
Fixed cursor glitch on all text input fields with only one line where cursor dropped down.
Changed new/rename file screen to be three lines instead of one, for long files.
Fixed memory bug in calculator.
Fixed keys being rather nonresponsive under mp3/ogg playback.
Added confirm delete option to scribble pad, todo, and addressbook.
Added text/html viewer, with up to 10 bookmarks per file.
Fixed potential cursor disappearing bug on the browser screen.
Fixed html viewer so if HTML tag is not found, that it still allows for rendering.
1.9 Preview 2

Changed color on INI/LNG syntax hilighting.
Added htm/html as an editable type, complete with syntax hilighting.
Rudimentary homebrew database, not very reliable due to early version of tcp, and not finished yet.
Enabled 'sleep' mode when lid is closed for power saving.
Touch area is bigger now for L/R/Start on screen.
Possibly fixed the issue with browser crashing.
Fixed random feature in music playback to never choose the same song twice.
Added ogg playback.
Added Id31.1 to mp3 playback.
Added double click mode in browser.
Added code from moonshell to boot sccf/scsd, this might or might not work.
Changed sound code to anti-alias sound, the method moonshell uses to make sound cleaner.
1.9 Preview

Added sanity check to filenames.
Fixed slight cursor issue with todo screen.
Fixed delete button not working on todo screen.
Fixed inconsistencies in file creation/saving on todo/scribble screens. Hopefully this fixes the SC SD errors for some.
Added wav playback to browser.
Added mod/s3m/xm/it playback to browser.
Added mp3 playback to browser.
Added slideshow controls to picture viewer.
Changed picture viewer to detect images too small to view.
Disabled write command on M3SD to stop corruption.
1.8

Reorganized calculator, added more commands, colored buttons.
Fixed bug with creating vCard files when no files are present.
Added a simple todo list app.
Added scribble pad with saving to bmp or png.
Fixed annoying bug where L button got random preses when using touchscreen.
Changed vCard detection to allow 3.0 cards.
Fixed typo in language files that caused browser formats not to be translated. Thanks Tostadilla.
1.7

Added JPEG viewer, supports Grayscale and H1V1, H1V2, H2V1, or H2V2 color compressions.
Added PNG viewer, supports all PNG files that can fit in memory.
Added BMP viewer, supports 2, 4, or 256 color, 16bit and 24bit files.
Added raw .bin viewer, supports 16bit color and 8bit color pallated 256x256 and 256x192 images.
Added syntax hilighting for .lng and .ini files in the text editor.
Potentially fixed shuddering bug in browser for some people.
Added GIF/Animated GIF viewer, supports all gifs that are small enough to be decompressed to memory. (falls back on streaming rendering of gifs, which can be rather slow).
Added HTML help for each page in DSOrganize. Hold select to view help on any page.
Added about page. Press start on the home screen to view credits.
Fixed memory function on calculator to preserve accuracy.
Fixed a text overflow error on the rename screen.
Added home/end buttons to text editor.
Added hide/unhide button to file browser.
Fixed bug in browser where choosing the ".." directory option broke directory browsing.
NeoFlash Special Edition

Changed the directory structure to have subdirectories as requested.
Added more file icons.
Internal files now launch to their respecive subprograms.
Added text editor.
Fixed crash bugs pertaining to calculator.
Redid internal memory structure for file and vCard lists to be unlimited.
Fixed issue with First and Last name setting overflowing sometimes.
Working message on calculator when running long operations.
Fixed bottom part of keyboard sometimes not responding.
Changed browser handling of empty directories to be far more stable.
Limiting implemented on calendar and day view screens to keep text onscreen.
1.62

Fixed issue where cursor would disappear after last character on addressbook.
Fixed issue with length of some fields being one less than needed.
1.61

Fix for small fonts not showing umlats, etc.
Fix for some things not being clickable with stylus in alternate languages.
1.6

Added a calculator!
Added option to hide hidden/system files on browser.
Hidden/system files now show up as greyed when visible.
Several new fields to be translated.
1.51

Added checking to fix freeze on .nds files run through boot managers like M3.
Added 'Rename' field to language parser. Sorry guys, slipped through the cracks.
1.5

Added file browser/nds launcher (NDS launcher for GBAMP only).
Fixed issue with slow repeat times in lists.
Added touch ability to select vcard/dayplanner/browser lists.
Fixed cursor disappearing bug when cancelling a created vCard.
Changed Day Planner to show current day on top screen, and added next/previous day buttons.
Fixed last wordwrap bug!
Seem to have fixed the data corruption bug in the Address viewer.
Many new translateable fields in this release!
Fixed uppercase chars being assigned to lowercase in translated files.
1.4

Added new translatable field "Unknown"
Redesigned text display library to handle foreign characters without crashing.
Added captions to homescreen buttons when not in english mode.
Fixed bug where pressing back in config mode did not always go back home.
Fixed a bug where calendar view didn't update Day Planner underlines properly.
Fixed issue with slow calendar load times (I think).
Added customizable keyboard layout to languages files, as well as special keyboard mode.
Added visual feedback when typing on the keyboard.
Fixed Prev Field/Next Field under Configuration not responding to touch.
Fixed calendar dates spilling over onto buttons at the bottom.
1.3

Fixed a bug with Edit DayView displaying wrong edit times.
Fixed the bug where DayView randomly lost entries (again).
Added 12/24 hour time and first/last name swap options.
Fixed special characters on the address display font.
Fixed cursor jumping back to current time when you cancel an edit on DayView and Address View.
1.21

Added configuration screen (currently nonfunctional).
Settings are now saved to a .ini file.
1.2

Archive of this release lost! If you have the information for this release, please edit it in!
1.1002

Added support for rudimentary handwriting recognition.
1.10001

Added experimental SC SD drivers.
1.1

Added addressbook reader
Initial Release

Calendar and Day Planner support
